### ISSUE TITLE
DNS lookups are expensive, IP validation is cheap

### ISSUE THREAD

**Issue by Ironholds** [hrbrmstr/iptools#14]
So let's see whether ASIO's DNS lookup is checking internally whether an IP is valid before dispatching it and trying to resolve it to a hostname. If the answer is "no" let's perform that check in the method; with buggy datasets we could save users a lot of time.

**Comment by hrbrmstr** [comment]
Whoa. +100. Super great idea.

**Comment by Ironholds** [comment]
@hrbrmstr looks like it completely shaves off the weird upper bound where things take 5s to resolve before timing out. Woot!

**Comment by Ironholds** [comment]
Okay, looks like that was a fluke of the benchmarking. Hrn; odd. I have modified it to support IPv6 IPs, though.
