### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by wrathematics** [hrbrmstr/iptools#15]
Hi,

I was able to get the package to build on Windows.  You can see my progress [here](https://github.com/wrathematics/iptools).  This requires some explanation, however.

* To build boost on windows, best as I can tell, you should download the source and navigate to the `boost_version` subtree (for me, `Sources/boost/snapshots/boost_1_54_0/`) and run  
  * `bootstrap.bat mingw`
  * `b2 toolset=gcc`
* It didn't do something reasonable like create `libboost_system.a` files.  Instead it appends some build information; for me that was `-mgw46-mt-1_54`.  This might seem reasonable, but as far as I know, ntfs doesn't support symlinking, so it's actually kind of insane.  It's entirely possible I just don't  know how to configure boost.  But I had to add that mess to the end of both `-lboost_system` and `-lboost_regex` in the `Makevars.win` file.

In addition, I made a few changes you probably want to keep regardless:

* I added the asio headers because why not.
* There were a ton of linker problems with `inet_pton()` which are fixed.

I was able to compile and  load the  package, but could not test it as all the tests were skipped, and I don't use testthat and don't care to look into why it does what it does.

My advice is to contact CRAN (since I'm guessing that's the end goal) and ask them about their setup with boost on Windows (or maybe you can infer it from winbuilder and/or another package?).  Shipping the source for system and regex is madness.  As the package is now, it's easy to install on  Linux and hard everywhere else.  That's what CRAN is good at imo.

Hope this helps.

**Comment by Ironholds** [comment]
Wait, so installing the boost executable...doesn't install boost?! What the hell, windows.

**Comment by Ironholds** [comment]
I just read http://fischerlaender.de/development/using-boost-c-libraries-with-gcc-g-under-windows - mind, blown.

**Comment by hrbrmstr** [comment]
I had a similar naming issue when I tried the Windows/Boost thing and just
gave up. I'm actually surprised anything works with R on Windows given the
bass ackwards mingw toolchain it's built from.

**Comment by Ironholds** [comment]
Sod it. Does it work on macs? If it can work on Unix then short of dirk descending from a cloud and explaining boost to us we might want to just call it 'done' for now. No objection TO windows support but nobody should drive themselves mad to provide it.

**Comment by hrbrmstr** [comment]
oh yeah. I built the orig on macs. I'll give the new one a go soon.

**Comment by wrathematics** [comment]
You can also just ship instructions for windows users to install it themselves.  There are a few packages that do this on CRAN, iirc.  But I can't remember any examples at the moment.  But you would need the fixes in my fork for them.

**Comment by Ironholds** [comment]
Honestly I've always felt pretty meh about that approach (I'll call it the "rJava approach" because that was the first example of "User does the heavy lifting" I saw in this environment). It's hard to ask users who don't have control over their development environment to do all of these complex compiled lang things, and I always feel bad about the risk that, if they can't make it work, I've offloaded the "problem" to them ("I can't make it work even with instructions, what's wrong with me"). This may be my own impostor syndrome talking and may not be a thing most windows users suffer from.

**Comment by wrathematics** [comment]
I'm really out of touch with what goes on in a windows user's mind.  I suspect most will just look at the instructions and go "fuck that".  But that's certainly possible.

**Comment by Ironholds** [comment]
Yeah, "bugger that" or "I tried and broke it" are both outcomes. If that's the expected outcome I'd say "let's go with mac + linux as platforms and hope boost get their shit together".

**Comment by wrathematics** [comment]
Keep betting on boost and you'll become a C programmer too 😉

Joking aside, that's a perfectly reasonable development strategy.  Feel free to close this as WONTFIX.

**Comment by Ironholds** [comment]
Sorry for wasting your time on it! :/

Okay; gonna close and go through the current implementation stripping out the existing windows-specific stuff (and amend the DESCRIPTION file). I guess the offer of a copy of @hrbrmstr 's book still stands, so maybe someone will be incentivised :D
