### ISSUE TITLE
CRAN release

### ISSUE THREAD

**Issue by Ironholds** [hrbrmstr/iptools#17]
Things to do for CRAN release:

1. Does it build flawlessly on macs?
2. Fix all the Warnings/Errors/NOTEs we can, have explanations for the rest;
3. Does "two platforms" mean unix + windows or two of (linux, mac, windows)?

**Comment by Ironholds** [comment]
@hrbrmstr working on teh macs yet?

**Comment by hrbrmstr** [comment]
works perfectly on Macs. 2 platforms == os x + linux. I'll see how many of
the warns/errs/etc I can remove over the wknd.

**Comment by Ironholds** [comment]
Awesome! :D

**Comment by hrbrmstr** [comment]
ON CRAN!
