### ISSUE TITLE
Feedback from Ripley - potential configure issue

### ISSUE THREAD

**Issue by hrbrmstr** [hrbrmstr/iptools#18]
First note:

   See http://cran.r-project.org/web/checks/check_results_iptools.html

   There is a bug in your configure script: clearly you did not test it without boost installed.

**Comment by hrbrmstr** [comment]
Well, it behaves just like RCurl does if curl devel libs are not present:

    install.packages("iptools")
    Installing package into ‘/usr/local/lib/R/site-library’
    (as ‘lib’ is unspecified)
    trying URL 'http://cran.rstudio.com/src/contrib/iptools_0.2.0.tar.gz'
    Content type 'application/x-gzip' length 264727 bytes (258 KB)
    ==================================================
    downloaded 258 KB

    * installing *source* package ‘iptools’ ...
    ** package ‘iptools’ successfully unpacked and MD5 sums checked
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking how to run the C preprocessor... gcc -E
    checking for R... yes
    checking for Rscript... yes
    checking whether we are using the GNU C++ compiler... yes
    checking whether g++ accepts -g... yes
    checking for boostlib >= 1.4... configure: We could not detect the boost libraries (version 1.4 or higher). If you have a staged boost library (still not installed) please specify $BOOST_ROOT in your environment and do not give a PATH to --with-boost option.  If you are sure you have boost installed, then check your version number looking in <boost/version.hpp>. See http://randspringer.de/boost for more documentation.
    ./configure: line 3555: exit: 1]: numeric argument required
    ERROR: configuration failed for package ‘iptools’
    * removing ‘/usr/local/lib/R/site-library/iptools’

**Comment by Ironholds** [comment]
@hrbrmstr any response? Fixed the other bug.

**Comment by Ironholds** [comment]
@jeroenooms any thoughts on this? You've got far more experience and knowledge in this sort of area than I. Is there something we should be doing we aren't or is CRAN being arbitrary?

**Comment by hrbrmstr** [comment]
https://cran.rstudio.com/web/checks/check_results_iptools.html still shows OS X issues and I have 2 new pings from BDR on this. Prbly need to work on it this week.

**Comment by jeroenooms** [comment]
Can't you just ship the required boost headers with the package?

**Comment by Ironholds** [comment]
We looked into that, iirc, and it was..."a pain".

**Comment by jeroenooms** [comment]
Yes I thought it was header only but you're actually using the libraries.

**Comment by jeroenooms** [comment]
Do you really need those libraries though? It seems like most things this package does can be implemented with some bitwise operators (netmasks) or os calls (resolve)? Why the heavy dependencies?

**Comment by hrbrmstr** [comment]
Convenience, mostly (at least for the IPv4 stuff). I did the bitwise
conversion changeover for the IPv4 functions in ipv4heatmap and cld port to
here.
