### ISSUE TITLE
Issue from SO

### ISSUE THREAD

**Issue by hrbrmstr** [hrbrmstr/iptools#20]
http://stackoverflow.com/questions/33605007/how-to-get-the-ip-address-from-the-domain-name-in-r

**Comment by Ironholds** [comment]
Wait, but we have this - it's the DNS lookup.

**Comment by hrbrmstr** [comment]
aye, but it's segfaulting in RStudio on the OPs system after [s]he reads in
domains from a CSV (and doesn't segfault in cmdling R)

**Comment by Ironholds** [comment]
Oh, that's really weird. I've encountered a couple of "works in the CLI, bugs in RStudio" bugs with other things - I wonder if this is at our end or not. Interested to see what shows up.

**Comment by hrbrmstr** [comment]
aye. I found another one that seems to be related to parallel processing
(my czdaptools pkg which is not C/++ based but does use parallel). I
figured if the OP gives me the file I can see what's up.
