### ISSUE TITLE
Non-Boost Asio is header-only

### ISSUE THREAD

**Issue by eddelbuettel** [hrbrmstr/iptools#21]
From the learn-something-new-everyday department: [asio](http://think-async.com/Asio) exists outside of Boost and is header-only.  

Couple that with regex in C++11 and you get a header-only package.  Useful?

**Comment by hrbrmstr** [comment]
ZOMGOSH YES! We may yet finally get this on Windows! #ty!!

**Comment by eddelbuettel** [comment]
Well ... Windows and C++11 are an issue, at least until R 3.3 and an updated toolchain (fingers crossed).  

But an AsioHeaders package may be a good idea <hint, hint>  ;-)

**Comment by hrbrmstr** [comment]
Ah, but we can use the regex functions in stringi, linking to it vs C++11
ones (I hit enter too soon :-). Making the pkg less dependent on full Boost
is huge either way.

On Tue, Dec 29, 2015 at 8:21 AM, Dirk Eddelbuettel <notifications@github.com

**Comment by eddelbuettel** [comment]
AFAIK based on a quick glimpse of the Asio site you can even continue to use Boost headers.  But it may free you from the dreaded linking issue -- and that alone is worth the price of admission.

**Comment by eddelbuettel** [comment]
I whipped up a quick package which you can find [here](https://github.com/eddelbuettel/asioheaders)

I compiles the following example from the Asio documentation just fine via `sourceCpp()`:

```C++
//
// timer.cpp
// ~~~~~~~~~
//
// Copyright (c) 2003-2015 Christopher M. Kohlhoff (chris at kohlhoff dot com)
//
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
//

#include <Rcpp.h>
#include <asio.hpp>
#include <boost/date_time/posix_time/posix_time.hpp>

// [[Rcpp::depends(BH)]]
// [[Rcpp::depends(AsioHeaders)]]

// [[Rcpp::export]]
int ex1() {
  asio::io_service io;

  asio::deadline_timer t(io, boost::posix_time::seconds(5));
  t.wait();

  Rcpp::Rcout << "Hello, world!" << std::endl;

  return 0;
}

/*** R
ex1()
*/

```

**Comment by hrbrmstr** [comment]
It seems to be missing the `local` directory. I copied that over from the `asio-1.10.6` distribution and built+installed the `AsioHeaders` package. Then, re-worked a local copy of `iptools` to use the non-Boost `asio` namespace. Got rid of all the `configure` BS and also the `Makevars.in` I had. 

It built and tests fine (on OS X at least…will try linux in a cpl mins).

It does also, however, toss out 71 warnings similar to this on build:

>In file included from asio_bindings.cpp:5:
>In file included from >/Library/Frameworks/R.framework/Versions/3.3/Resources/library/AsioHeaders/include/asio.hpp:27:
>/Library/Frameworks/R.framework/Versions/3.3/Resources/library/AsioHeaders/include/asio/basic_signal_set.hpp:375:55: warning: unused typedef 'type_check' [-Wunused-local-typedef]
>    ASIO_SIGNAL_HANDLER_CHECK(SignalHandler, handler) type_check;

**Comment by hrbrmstr** [comment]
Just tested my modified `AsioHeaders` and hacked `iptools` on Ubuntu 14.04, R 3.2.1 and it works perfectly! All tests pass without issue (and those `type_check` warnings do not show up there)

**Comment by hrbrmstr** [comment]
ZOMGOSH I GOT `iptools` WORKING ON WINDOWS WITH THIS (cc: @Ironholds !!!)

**Comment by eddelbuettel** [comment]
I tried a casual check via recursive grep and you currently seem to be the only ones including `asio.hpp`.

That said, many people have networking code (often older, poorer C code and interfaces) so I think getting AsioHeaders onto CRAN is a 'Good Thing (TM)'.  I'll work on that.

Can you send me a PR with the changes it needed?  That wasn't clear to me based on this thread.

**Comment by hrbrmstr** [comment]
Aye. Will do. I'm triple checking what I've done first to make absolutely
sure including the `local` directory is necessary. This is EPIC! #ty

**Comment by eddelbuettel** [comment]
DANG.  `local/` is in my `.gitignore`.  Will adjust.   Check back in a minute or two.

**Comment by eddelbuettel** [comment]
Try refreshing your repo now.  Magically `/inst/include/asio/local/` now appears.

Sorry about earlier omission.

**Comment by hrbrmstr** [comment]
Ah! Very cool. Works perfectly. Thx again for this. It'll rly help get more "cyber-y" pkgs into the R ecosystem.

**Comment by eddelbuettel** [comment]
I'll get this off to CRAN today then.

**Comment by hrbrmstr** [comment]
Tested:

    devtools::install_github("eddelbuettel/asioheaders")
    devtools::install_github("hrbrmstr/iptools")

on Windows x64, OS X & Ubuntu 14.0.4. It works. This is the best new year's present ever :-)

**Comment by Ironholds** [comment]
YAY! Dirk, you are (as you hopefully well know) a gentleman and a scholar.

@hrbrmstr you realise you have to send @eddelbuettel a book now, right? ;)

**Comment by hrbrmstr** [comment]
Ah, yes! I will gladly send Dirk a copy of the book (would you like e-copy
or dead-tree, my good sir? :-)

**Comment by eddelbuettel** [comment]
Oh, the virtual (tweeted) pat-on-the-back was just fine ...

**Comment by eddelbuettel** [comment]
Now in CRAN's incoming.

**Comment by hrbrmstr** [comment]
Wow. That was fast! Thank ye again!

**Comment by hrbrmstr** [comment]
Top of the New Year, @eddelbuettel! Did the CRAN folks provide any feedback on this? I fear I may have DoS'd them looking at the CRAN pkg incoming temporal view :-)

**Comment by eddelbuettel** [comment]
We are argueing over authorship attribution.  

They want the Asio author(s) as Authors of the R package. I happen to disagree.

**Comment by Ironholds** [comment]
Huh. I mean I can see [cph] maybe, but..

**Comment by eddelbuettel** [comment]
I also asked them compare [doc/AUTHORS](https://github.com/wch/r-source/blob/trunk/doc/AUTHORS) with [doc/COPYRIGHTS](https://github.com/wch/r-source/blob/trunk/doc/COPYRIGHTS) one of these days...

(And yes, he meant cph but I don't do Authors@R which I find abysmal.  Chacun a son gout...)

I am turning it into an installer package.  F'off to enforced co-authorship. My package. My work. My rules.

**Comment by eddelbuettel** [comment]
Quick update on this:  prepared a new minimal _installer_ package (size: 3kb) which simply downloads the Asio headers upon package build, which I dropped into incoming yesterday late afternoon.  

CRAN still deciding whether to be mad or really mad ...   But hey, I am Policy Compliant (TM), and I am not the one who made up the foolish rules.

**Comment by hrbrmstr** [comment]
nice. Don't they complain when a pkg directly has ".hpp" files in it but
not complain if it's doing the install via this method as well?

**Comment by eddelbuettel** [comment]
Not sure.  They do dislike `src/*.hpp` as I recall -- but package BH is shockblockafull of `*.hpp` as well.

**Comment by eddelbuettel** [comment]
CRAN and I are still negotiating over the fate of the hostages^Hpackage.  Sit tight. In another year or two we may have something...
