### ISSUE TITLE
0.3.0 CRAN Submission

### ISSUE THREAD

**Issue by hrbrmstr** [hrbrmstr/iptools#23]
All the code's been updated to work with the CRAN `AsioHeaders`. I also got rid of the `#pragma` warnings on non-OS X systems.

I've tested it on

- [x] R stable & devel on OS X
- [x] R stable on Windows 7
- [x] R devel on Ubuntu 14.04

and am just waiting for `AsioHeaders` to get to whatever repo WinBuilder uses to do a remote test there before submitting it to the CRAN overlords. Will keep this open until that's done.

**Comment by Ironholds** [comment]
Sweeeet!

**Comment by hrbrmstr** [comment]
Done.
