### ISSUE TITLE
ip_in_range always returns TRUE for /32 ranges

### ISSUE THREAD

**Issue by tdsmith** [hrbrmstr/iptools#26]
If `ranges` contains a /32, `ip_in_range` always returns `TRUE`.

Ex:
```r
> ip_in_range("8.8.8.8", "127.0.0.1/32")
[1] TRUE
```

I'm seeing this with CRAN version 0.3.0.

**Comment by hrbrmstr** [comment]
thx. will take a look in the AM

**Comment by tdsmith** [comment]
This occurs because the mask is calculated (line 247 of asio_bindings.cpp) as
`unsigned int mask = ~(0xffffffff >> slash_val);`

`0xffffffff >> 32` is undefined behavior; in clang, the answer is 0xffffffff and not the expected 0x0, so `mask` takes the value `0x0`.

Demo:
```c
#include <stdio.h>

int main() {
    unsigned int google = 134744072; // 8.8.8.8
    unsigned int slash_val = 32;
    unsigned int notmask = 0xffffffff >> slash_val;
    unsigned int mask = ~(0xffffffff >> slash_val);
    unsigned int cidr_int = google & mask;

    printf("%u %u %u %u %u\n", google, slash_val, notmask, mask, cidr_int);
}
```
