### ISSUE TITLE
R minimum version

### ISSUE THREAD

**Issue by hrbrmstr** [hrbrmstr/iptools#28]
@Ironholds, since we link to Rcpp which has an R dep of >= 3.0.0, doesn't that by default mean we have said minimum dep?

**Comment by Ironholds** [comment]
@hrbrmstr yes/no; for users that already have or manually install Rcpp it should be fine, but for users who haven't, 3.0.0 is basically a minimum. Are you thinking about making it explicit in the DESCRIPTION?
