### ISSUE TITLE
0.7.2 retired from CRAN 😟 

### ISSUE THREAD

**Issue by HenningLorenzen-ext-bayer** [hrbrmstr/iptools#43]
- https://cran-archive.r-project.org/web/checks/2023/2023-02-20_check_results_iptools.html
- http://dirk.eddelbuettel.com/cranberries/2023/02/20#iptools-0.7.2

**Comment by hrbrmstr** [comment]
Yes. {ipaddress} has almost all the functionality, and the pkg is still on
GH.

If someone else wants to play along with capricious decisions in R land,
they are welcome to take over the package.

**Comment by wibeasley** [comment]
It sounds like there are no plans to develop this more or put this back on CRAN? If so, I'll take this off of the [Web Technology](https://cran.r-project.org/view=WebTechnologies) task view and point to {ipaddress}.  But please [tell](https://github.com/cran-task-views/WebTechnologies/issues) @pachadotdev or me if I'm misunderstanding or something changes and you'd like it back on.

**Comment by hrbrmstr** [comment]
I have no plans to put {iptools} back on CRAN. {ipaddress} is the natural
successor. As such, it definitely makes sense to remove it from the task
view.

As noted, if someone else wants to take over {iptools} I'll let CRAN know
that.
