### ISSUE TITLE
iptools removed from CRAN

### ISSUE THREAD

**Issue by meystingray** [hrbrmstr/iptools#44]
https://cran-archive.r-project.org/web/checks/2023/2023-02-20_check_results_iptools.html

Any plans to get this awesome package back online?

**Comment by hrbrmstr** [comment]
Well met!

{ipaddress} does (I think, now) 100% of this. If not, I'm more than willing
to hand it over to someone who would like to deal with CRAN's inanity.

**Comment by meystingray** [comment]
It's ok...i'll switch over to ipaddress. I did like the is_valid and validate_range functions...thanks for the package.
